name: mrcode
adopt-info: mrcode
summary: MrCode. Code editing.
description: |
  MrCode is an editor based on Visual Studio Code.

base: core18
grade: stable
confinement: classic

parts:
  mrcode:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      # Get GitHub releases
      wget --quiet https://api.github.com/repos/zokugun/MrCode/releases/latest -O latest.json
      VERSION=$(jq -r .tag_name latest.json)
      DEB_URL=$(grep browser_download latest.json | grep deb\" | grep $ARCHITECTURE | grep -v sha256 | cut -d'"' -f4 | tail -n 1)
      DEB=$(basename "${DEB_URL}")
      # Downloading .deb"
      wget "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Unpacking .deb"
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f latest.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Correct path to icon.
      sed -i 's|Icon=mrcode|Icon=${SNAP}/usr/share/pixmaps/mrcode.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/mrcode.desktop
      sed -i 's|Exec=/usr/share/mrcode/mrcode|Exec=mrcode|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/mrcode.desktop
      sed -i 's|Icon=mrcode|Icon=/usr/share/pixmaps/mrcode.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/mrcode-url-handler.desktop
      # Set version
      echo $VERSION > $SNAPCRAFT_STAGE/version
      snapcraftctl set-version "$VERSION"
    build-packages:
      - dpkg
      - jq
      - sed
      - wget
    stage-packages:
      - ibus-gtk3
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgbm1
      - libgtk-3-0
      - libxkbfile1
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxshmfence1
      - libxss1
      - libxtst6
      - zlib1g
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man

  electron-launch:
    after:
      - mrcode
    plugin: dump
    source: snap/local

apps:
  mrcode:
    command: electron-launch $SNAP/usr/share/mrcode/bin/mrcode --no-sandbox
    common-id: mrcode.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/mrcode/bin/mrcode --open-url --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
