name: Publish AUR package
description: Publish AUR package
branding:
  color: green
  icon: upload
inputs:
  package_name:
    description: Name of the package to publish
    required: true
  package_version:
    description: Version of the package to publish
    required: false
  commit_message:
    description: Message to use when commiting
    required: false
    default: Update ${package_name} to ${package_version}
runs:
  using: docker
  image: Dockerfile
