name: Publish AUR package
description: Publish AUR package
branding:
  color: green
  icon: upload
inputs:
  package_name:
    description: Name of the package to publish
    required: true
  package_version:
    description: Version of the package to publish
    required: false
  package_type:
    description: Type of the package to publish
    required: false
    default: stable
  commit_message:
    description: Message to use when commiting
    required: false
    default: Update ${package_name} to ${package_version}
  depends:
    description: List of additional dependencies to install
    required: false
  post_depends:
    description: Script to execute after installation of dependencies
    required: false
runs:
  using: docker
  image: Dockerfile
