name: linux

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        OS_NAME: 'linux'
        VSCODE_ARCH: ${{ matrix.vscode_arch }}

    strategy:
      fail-fast: false
      matrix:
        vscode_arch: [x64, arm64, armhf]
        include:
        - vscode_arch: x64
          npm_arch: x64
          image: vscodium/vscodium-linux-build-agent:bionic-x64
        - vscode_arch: arm64
          npm_arch: arm64
          image: vscodium/vscodium-linux-build-agent:stretch-arm64
        - vscode_arch: armhf
          npm_arch: armv7l
          image: vscodium/vscodium-linux-build-agent:stretch-armhf

    steps:
      - uses: actions/checkout@v2

      - name: Install GH
        run: ./install_gh.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clone VSCodium repo
        env:
          RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
          VSCODIUM_LATEST: ${{ secrets.VSCODIUM_LATEST }}
        run: ./get_repo.sh

      - name: Prepare VSCodium
        run: ./prepare.sh

      - name: Check existing MrCode tags/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./vscodium
        run: ./check_tags.sh

      - name: Get Source Version
        run: ./version.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_arch }}
        working-directory: ./vscodium
        run: ./build.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Prepare artifacts
        working-directory: ./vscodium
        run: ./prepare_artifacts.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./vscodium
        run: ./release.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Update versions repo
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        working-directory: ./vscodium
        run: ./update_version.sh
        if: env.SHOULD_BUILD == 'yes'

  aur:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Register local actions
        uses: actions/checkout@master
        env:
          PUBLISH_AUR: ${{ secrets.PUBLISH_AUR }}
        if: env.PUBLISH_AUR != 'no'

      - name: Publish mrcode-bin
        uses: ./.github/actions/publish-aur-package
        with:
          package_name: mrcode-bin
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
          GIT_USERNAME: ${{ secrets.AUR_GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.AUR_GIT_EMAIL }}
          PUBLISH_AUR: ${{ secrets.PUBLISH_AUR }}
        if: env.PUBLISH_AUR != 'no'

      - name: Publish mrcode
        uses: ./.github/actions/publish-aur-package
        with:
          package_name: mrcode
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
          GIT_USERNAME: ${{ secrets.AUR_GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.AUR_GIT_EMAIL }}
          PUBLISH_AUR: ${{ secrets.PUBLISH_AUR }}
        if: env.PUBLISH_AUR != 'no'

      - name: Publish mrcode-git
        uses: ./.github/actions/publish-aur-package
        with:
          package_name: mrcode-git
          package_type: rolling
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
          GIT_USERNAME: ${{ secrets.AUR_GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.AUR_GIT_EMAIL }}
          PUBLISH_AUR: ${{ secrets.PUBLISH_AUR }}
        if: env.PUBLISH_AUR != 'no'

  snap:
    needs: release
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        env:
          PUBLISH_SNAP: ${{ secrets.PUBLISH_SNAP }}
        if: env.PUBLISH_SNAP != 'no'

      - name: Build snap
        id: build
        uses: snapcore/action-build@v1
        with:
          path: stores/snapcraft
        env:
          PUBLISH_SNAP: ${{ secrets.PUBLISH_SNAP }}
        if: env.PUBLISH_SNAP != 'no'

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        env:
          PUBLISH_SNAP: ${{ secrets.PUBLISH_SNAP }}
        if: env.PUBLISH_SNAP != 'no'
