name: windows

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  windows:
    runs-on: windows-2016
    env:
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
      OS_NAME: 'windows'
    strategy:
      fail-fast: false
      matrix:
        vscode_arch: [x64, ia32, arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Python 2
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'

      - name: Clone VSCodium repo
        run: ./get_repo.sh
        shell: bash

      - name: Prepare VSCodium
        run: ./prepare.sh
        shell: bash

      - name: Check existing VSCodium tags/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./vscodium
        run: ./check_tags.sh
        shell: bash

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.vscode_arch }}
          npm_config_target_arch: ${{ matrix.vscode_arch }}
        working-directory: ./vscodium
        run: ./build.sh
        shell: bash
        if: env.SHOULD_BUILD == 'yes'

      - name: Move/rename build artifacts
        working-directory: ./vscodium
        run: |
          mv vscode\\.build\\win32-${VSCODE_ARCH}\\system-setup\\VSCodeSetup.exe MrCodeSetup-${VSCODE_ARCH}-${LATEST_MS_TAG}.exe
          mv vscode\\.build\\win32-${VSCODE_ARCH}\\user-setup\\VSCodeSetup.exe MrCodeUserSetup-${VSCODE_ARCH}-${LATEST_MS_TAG}.exe
          mv vscode\\.build\\win32-${VSCODE_ARCH}\\archive\\VSCode-win32-${VSCODE_ARCH}.zip MrCode-win32-${VSCODE_ARCH}-${LATEST_MS_TAG}.zip
        shell: bash
        if: env.SHOULD_BUILD == 'yes'

      - name: Generate shasums
        working-directory: ./vscodium
        run: ./sum.sh
        shell: bash
        if: env.SHOULD_BUILD == 'yes'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.SHOULD_BUILD == 'yes'
        with:
          tag_name: ${{ env.LATEST_MS_TAG }}
          files: |
            ./vscodium/*.sha256
            ./vscodium/MrCode*.zip
            ./vscodium/MrCodeUserSetup*.exe
            ./vscodium/MrCodeSetup*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update versions repo
        working-directory: ./vscodium
        if: env.SHOULD_BUILD == 'yes'
        run: ./update_version.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}

